version: "3.9"
services:
  product-service:
    build:
      context: ./product-service
    ports:
      - "5001:5001"

  order-service:
    build:
      context: ./order-service
    ports:
      - "5002:5002"
    depends_on:
      - product-service

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "5003:5003"

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "5000:5000"
    depends_on:
      - product-service
      - order-service
      - inventory-service
